apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-canary-b
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /eatzzy(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: frontend-svc-b
            port:
              number: 80
